name: Feature request
description: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe what you're doing and where it gets in your way.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've tried
  - type: checkboxes
    id: help
    attributes:
      label: Contributing
      options:
        - label: I'd be willing to send a pull request
